### ISSUE TITLE
Quartz job to send email using FreeMarker template

### ISSUE THREAD

**Issue by jweyrich** [caelum/vraptor-simplemail#16]
How can a Quartz job send an email that depends on a FreeMarker template?

I noticed that the `DefaultTemplateMail` needs an instance of `Freemarker` to be injected, however, the default implementation [FreemarkerEngine from vraptor-freemarker](https://github.com/caelum/vraptor-freemarker/blob/0c9425c7365efaadc2374fa072ca550aecd608bf/src/main/java/br/com/caelum/vraptor/freemarker/FreemarkerEngine.java) depends on `HttpServletResponse`. Since a Quartz job doesn't run within a servlet request, _I believe_ the support to send emails from a Quartz job doesn't exist yet. What would you recommend to accomplish this?

**Comment by csokol** [comment]
Hi,

How you execute this quartz job? There's a solution (not very elegant): in
your job you could send a request to your app and in the controller you can
inject simple mail classes.

This plugin: https://github.com/caelum/vraptor-quartzjob allow you to
inject request scoped components inside your jobs (it basically create
quartz jobs that send requests to your application).

## 

Chico Sokol

**Comment by jweyrich** [comment]
Right. I'm actually using [vraptor-tasks](https://github.com/wpivotto/vraptor-tasks) to manage the jobs for me. It has a `DefaultRequestScopedTask` that (I believe) does exactly what you suggest.
I'd prefer not to expose an extra method just to solve this, but if that's really the only way...
Do you think it's possible to mock a request instance and inject it only in those dependents? Probably using Mockito and Guice.

**Comment by guilhermesilveira** [comment]
You can use vraptor simple mail plug in with vraptor quartz job plug in.

The simple main plug-ins supports freemarker templates out of the box

**Comment by csokol** [comment]
Try to build the simplemail class by hand and pass a
MockHttpServletResponse to freemarker engine.
This might work since vraptor-simplemail should not write anything to the
response.

But I think that this solution is worse than any of the others we
discussed...

## 

Chico Sokol

**Comment by csokol** [comment]
@jweyrich, may I close this issue? (since there's nothing we can do here in vraptor-simplemail...)

**Comment by jweyrich** [comment]
@csokol right, I believe I should've opened an issue for `vraptor-freemarker` instead. I just didn't know this at the time. Thank you for the support nevertheless :-)

FWIW, I solved this by writing custom classes that implement `br.com.caelum.vraptor.freemarker.Freemarker` and `br.com.caelum.vraptor.freemarker.Template`. The new implementations don't depend on `HttpServletResponse`, nor `Result`. Take a look at [this Gist](https://gist.github.com/jweyrich/7896735). If anyone is interested, I could try to refactor these and send a pull request to `vraptor-freemarker` -  I suspect other people might benefit from it.
