### ISSUE TITLE
Configurando Ambiente

### ISSUE THREAD

**Issue by ghost** [caelum/vraptor-simplemail#2]
Guilerme não consigo acessar o meu arquivo de propriedades, mesmo colocando o development.properties no diretorio src/main/resources

**Comment by danilomiranda** [comment]
Estou enfrentando o mesmo problema! 
@sergioholanda  voce consegui resolver este problema?

**Comment by luiz** [comment]
Oi, pessoal! Como vocês estão tentando acessá-lo? Qual o código que não funciona?

**Comment by danilomiranda** [comment]
OI @luiz 

Segue meu código:
<code>
//imports
@Resource
public class EstateController {

private final Environment environment;
public EstateController(Environment environment) {
        this.environment = environment;
}
@Path("/contact")
    @Post
    @Public
    public void sendContact(MessageContact messageContact) {
        Email email = new SimpleEmail();
        email.setSubject(messageContact.getName() + " entrou em contato.");
        System.out.println(environment
                .supports("vraptor.simplemail.main.password"));
        try {
            email.addTo(messageContact.getEmail());
            email.setMsg(messageContact.getMessage());
//          mailer.send(email); // Hostname, port and security settings are made
                                // by the Mailer
        } catch (EmailException e) {
            // TODO Auto-generated catch block
            System.out.println(e);
        }
    }
}

</code>

Neste sysout ele escreve "false"

**Comment by danilomiranda** [comment]
Configurei o web.xml e coloquei os arquivos .properties no diretório src/main/resources conforme a documentação do plugin.

**Comment by luiz** [comment]
E como está a configuração no seu web.xml e o seu development.properties?

**Comment by danilomiranda** [comment]
web.xml
<code>
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://java.sun.com/xml/ns/javaee" xmlns:web="http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd"
    xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd"
    id="WebApp_ID" version="2.5">
    <display-name>s3it-estate</display-name>
    <context-param>
        <param-name>javax.servlet.jsp.jstl.fmt.localizationContext</param-name>
        <param-value>messages</param-value>
    </context-param>
    <context-param>
        <param-name>br.com.caelum.vraptor.environment</param-name>
        <param-value>production</param-value>
    </context-param>
    <context-param>
        <param-name>br.com.caelum.vraptor.packages</param-name>
        <param-value>br.com.caelum.vraptor.util.jpa</param-value>
    </context-param>
    <filter>
        <filter-name>vraptor</filter-name>
        <filter-class>br.com.caelum.vraptor.VRaptor</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>vraptor</filter-name>
        <url-pattern>/*</url-pattern>
        <dispatcher>FORWARD</dispatcher>
        <dispatcher>REQUEST</dispatcher>
    </filter-mapping>
</web-app>
</code>

development.properties
<code>
environment.controller = true
vraptor.simplemail.main.server = smtp.gmail.com
vraptor.simplemail.main.port = 465
vraptor.simplemail.main.tls = false
vraptor.simplemail.main.from = xxxxx@gmail.com
vraptor.simplemail.main.replyTo = support@xxx.com
vraptor.simplemail.main.username = xxxxxxx
vraptor.simplemail.main.password = xxxxx
</code>

**Comment by luiz** [comment]
Oi, @danilomiranda 

No seu caso, parece estar devolvendo false porque você configurou o ambiente como sendo production no web.xml, mas está tentando ler o development.properties. Quando o ambiente é production, ele tenta ler o production.properties.

**Comment by danilomiranda** [comment]
@luiz 

Falha minha coloquei o development.properties aqui. Mas acontece que o production.properties esta exatamente igual ao development...

**Comment by luiz** [comment]
Opa, uma falha minha também. O método supports do Environment tenta transformar o valor que está na chave passada para ele em um boolean. Ou seja, se está devolvendo false, ele está encontrando seu production.properties; se ele não estivesse encontrando, você estaria recebendo uma NoSuchElementException.

**Comment by danilomiranda** [comment]
Então @luiz eu debuguei aqui e abri a árvore do objeto environment e achei os atributos que configurei dentro do production.properties
Então a confusão foi esse false que estava retornando, eu imaginei que ele iria mostrar true caso encontrasse o atributo

Só que o plugin ainda não está enviando email, quando ele entra na chamada ( mailer.send(email);)
a app fica processando infinitamente.
Já verifiquei o usuario, senha e configurações do servidor e está tudo ok.

**Comment by luiz** [comment]
@danilomiranda dei uma checada na configuração que usamos em um projeto aqui para mandar e-mail pelo GMail e parece que o problema pode ser nessas configurações. Aqui usamos os seguintes valores:

```
vraptor.simplemail.main.server = smtp.gmail.com
vraptor.simplemail.main.port = 587
vraptor.simplemail.main.tls = true
```

Tenta com essas configurações (da porta e do TLS) para ver se vai.

**Comment by danilomiranda** [comment]
@luiz funcionou, estranho eu utilizava esta configuração em outro sistema e até a última vez que usei estava funcionando.
Valeu pela ajuda!!

**Comment by luiz** [comment]
Que bom!
Vou fechar essa issue, então.
