### ISSUE TITLE
Problema com mailer.send(email);

### ISSUE THREAD

**Issue by tzattera** [caelum/vraptor-simplemail#8]
Olá pessoal.

Estou com um problema e não consigo resolver. Instalei vraptor-simplemail e não consigo enviar emails.. O problema é que a chamada do método mailer.send(email) não gera exceção nenhuma, mas também não envia o email!

Se alguém puder me ajudar agradeço.

---

development.properties
environment.controller = true
vraptor.simplemail.main.server = smtp.gmail.com
vraptor.simplemail.main.port = 587
vraptor.simplemail.main.tls = true
vraptor.simplemail.main.from = contato@minhaEmpresa.com
vraptor.simplemail.main.replyTo = contato@minhaEmpresa.com
vraptor.simplemail.main.username = contato@minhaEmpresa.com
vraptor.simplemail.main.password = minhaSenha

---

public void sendEmailContact(String name, String emailAdress, String site,
            String subject, String message) throws BusinessException {

```
    // a linha abaixo printa "smtp.gmail.com"
    System.out.println(environment.get("vraptor.simplemail.main.server"));

    if(message != null && emailAdress != null){
        try {
            Email email = new SimpleEmail();
            email.addTo("contato@minhaEmpresa.com");
            email.setMsg(message);
            email.setSubject(subject);
            email.setFrom(emailAdress, name);
            mailer.send(email); // Hostname, port and security settings are made by the Mailer

        } catch (EmailException e) {
            e.printStackTrace(); // nunca cai na exception
        }

    }

    // após executar o send, cai na linha abaixo 
    result.redirectTo("http://minhaEmpresa.com");
}
```

}

**Comment by luiz** [comment]
Oi, @tzattera 

O problema é que você está colocando essa configuração no development.properties, ou seja, no arquivo do ambiente de desenvolvimento. O vraptor-simplemail não envia o e-mail de verdade nesse caso. Ele envia apenas se você estiver em produção, ou seja, com o ambiente configurado para "production".

Tente salvar esse arquivo como production.properties, mudar o environment para production e veja se envia de verdade.

**Comment by tzattera** [comment]
Muito obrigado luiz. Anteriormente eu estava com outros problemas de configuração e pouco antes de acertá-los acabei trocando para o "development". Funcionou perfeitamente. Muito obrigado.

**Comment by csokol** [comment]
Só pra esclarecer, o vraptor-simplemail envia os emails quando o
ambiente não é development, certo? Qualquer outro ambiente diferente
de development ele usa o DefaultMailer ou o que estiver configurado no
environment com a chave "mailer.implementation"

https://github.com/caelum/vraptor-simplemail/blob/master/src/main/java/br/com/caelum/vraptor/simplemail/MailerFactory.java

## 

Chico Sokol

2013/6/7 tzattera notifications@github.com:

**Comment by luiz** [comment]
Isso! Desculpe, confundi com o código que você fez no AmazonSESMailer,
@csokol.

**Comment by csokol** [comment]
(que bom que alguém leu :)

Aproveitando, o SESMailer só enviava emails em production, eu mudei isso
pra ele mandar os emails se estiver em productions OU se estiver
configurado no environment. Tudo bem, né?

## 

Chico Sokol

**Comment by luiz** [comment]
Acho que sim! Só documentar direitinho quando fizer release :)
